/* Camper Compagnon — automatische gewichtsschatting.
   WEIGHTS: trefwoord (NL, lowercase) → typisch gewicht in gram per stuk.
   Matching is case-insensitive op substring; het LANGSTE passende trefwoord
   wint, zodat "pannenkoekenmix" niet op "pan" matcht. Vrij uit te breiden:
   voeg gewoon een regel toe. */

export const WEIGHTS = [
  /* ---- dranken ---- */
  { kw: 'fles water 1,5', g: 1550 },
  { kw: 'fles water 1.5', g: 1550 },
  { kw: 'fles water 0,5', g: 550 },
  { kw: 'fles water', g: 1550 },
  { kw: 'flesje water', g: 550 },
  { kw: 'sixpack water', g: 9300 },
  { kw: 'krat bier', g: 17000 },
  { kw: 'sixpack bier', g: 2300 },
  { kw: 'blikje bier', g: 360 },
  { kw: 'blik bier', g: 360 },
  { kw: 'fles bier', g: 550 },
  { kw: 'fles wijn', g: 1200 },
  { kw: 'wijn', g: 1200 },
  { kw: 'cassis', g: 1600 },
  { kw: 'cola', g: 1600 },
  { kw: 'sinas', g: 1600 },
  { kw: 'frisdrank', g: 1600 },
  { kw: 'pak melk', g: 1060 },
  { kw: 'sojamelk', g: 1060 },
  { kw: 'havermelk', g: 1060 },
  { kw: 'melk', g: 1060 },
  { kw: 'appelsap', g: 1060 },
  { kw: 'sinaasappelsap', g: 1060 },
  { kw: 'pak sap', g: 1060 },
  { kw: 'drinkpakje', g: 220 },
  { kw: 'koffiecups', g: 120 },
  { kw: 'koffiebonen', g: 500 },
  { kw: 'koffiepads', g: 270 },
  { kw: 'oploskoffie', g: 230 },
  { kw: 'pak koffie', g: 500 },
  { kw: 'koffie', g: 500 },
  { kw: 'thee', g: 100 },

  /* ---- conserven & potten ---- */
  { kw: 'blik soep', g: 450 },
  { kw: 'blik tomaten', g: 460 },
  { kw: 'tomatenblokjes', g: 460 },
  { kw: 'blik groente', g: 460 },
  { kw: 'blik mais', g: 380 },
  { kw: 'blik bonen', g: 460 },
  { kw: 'blik knakworst', g: 450 },
  { kw: 'blik tonijn', g: 180 },
  { kw: 'blik vis', g: 180 },
  { kw: 'blik', g: 450 },
  { kw: 'pot pastasaus', g: 650 },
  { kw: 'pastasaus', g: 650 },
  { kw: 'pot appelmoes', g: 900 },
  { kw: 'appelmoes', g: 900 },
  { kw: 'pot jam', g: 600 },
  { kw: 'jam', g: 600 },
  { kw: 'pot augurken', g: 720 },
  { kw: 'pot olijven', g: 350 },
  { kw: 'pot', g: 500 },

  /* ---- droogwaren & ontbijt ---- */
  { kw: 'penne', g: 500 },
  { kw: 'spaghetti', g: 500 },
  { kw: 'macaroni', g: 500 },
  { kw: 'pasta', g: 500 },
  { kw: 'rijst', g: 1000 },
  { kw: 'couscous', g: 500 },
  { kw: 'bloem', g: 1000 },
  { kw: 'pannenkoekenmix', g: 450 },
  { kw: 'poedersuiker', g: 300 },
  { kw: 'suiker', g: 1000 },
  { kw: 'zakje suiker', g: 50 },
  { kw: 'crackers', g: 250 },
  { kw: 'rijstwafels', g: 130 },
  { kw: 'beschuit', g: 140 },
  { kw: 'ontbijtkoek', g: 500 },
  { kw: 'muesli', g: 500 },
  { kw: 'cornflakes', g: 400 },
  { kw: 'havermout', g: 500 },
  { kw: 'afbakbroodjes', g: 300 },
  { kw: 'stokbrood', g: 250 },
  { kw: 'brood', g: 800 },
  { kw: 'pindakaas', g: 600 },
  { kw: 'hagelslag', g: 400 },
  { kw: 'chocopasta', g: 600 },
  { kw: 'stroop', g: 600 },
  { kw: 'honing', g: 450 },
  { kw: 'chips', g: 200 },
  { kw: 'koekjes', g: 300 },
  { kw: 'proteïnereep', g: 60 },
  { kw: 'proteinereep', g: 60 },
  { kw: 'reep', g: 50 },
  { kw: 'shake', g: 1000 },

  /* ---- kruiden, sauzen & olie ---- */
  { kw: 'zout', g: 600 },
  { kw: 'peper', g: 100 },
  { kw: 'aromat', g: 90 },
  { kw: 'viskruiden', g: 60 },
  { kw: 'aardappelkruiden', g: 60 },
  { kw: 'kruiden', g: 60 },
  { kw: 'olijfolie', g: 920 },
  { kw: 'zonnebloemolie', g: 920 },
  { kw: 'olie', g: 920 },
  { kw: 'azijn', g: 1000 },
  { kw: 'mayonaise', g: 700 },
  { kw: 'ketchup', g: 550 },
  { kw: 'curry', g: 550 },
  { kw: 'ketjap', g: 700 },
  { kw: 'joppiesaus', g: 500 },
  { kw: 'jippiesaus', g: 500 },
  { kw: 'pesto', g: 200 },
  { kw: 'saus', g: 500 },

  /* ---- koeling & vers ---- */
  { kw: 'kwark', g: 550 },
  { kw: 'yoghurt', g: 1060 },
  { kw: 'vla', g: 1060 },
  { kw: 'boter', g: 270 },
  { kw: 'crème de brie', g: 150 },
  { kw: 'creme de brie', g: 150 },
  { kw: 'brie', g: 200 },
  { kw: 'kaas', g: 500 },
  { kw: 'beleg', g: 150 },
  { kw: 'eieren', g: 700 },
  { kw: 'garnalen', g: 200 },
  { kw: 'pangafilet', g: 400 },
  { kw: 'zalm', g: 250 },
  { kw: 'kipfilet', g: 500 },
  { kw: 'gehakt', g: 500 },
  { kw: 'worst', g: 250 },
  { kw: 'appels', g: 1000 },
  { kw: 'appel', g: 180 },
  { kw: 'banaan', g: 120 },
  { kw: 'bananen', g: 700 },
  { kw: 'sinaasappel', g: 200 },
  { kw: 'komkommer', g: 400 },
  { kw: 'tomaten', g: 500 },
  { kw: 'paprika', g: 200 },
  { kw: 'sla', g: 300 },
  { kw: 'blokjes aardappelen', g: 800 },
  { kw: 'aardappelen', g: 2500 },
  { kw: 'fruitzakje', g: 100 },

  /* ---- huishouden & verzorging ---- */
  { kw: 'wc-papier', g: 1100 },
  { kw: 'wc papier', g: 1100 },
  { kw: 'toiletpapier', g: 1100 },
  { kw: 'keukenrol', g: 450 },
  { kw: 'afwasmiddel', g: 550 },
  { kw: 'afwasborstel', g: 50 },
  { kw: 'wasmiddel', g: 1100 },
  { kw: 'wasmiddeldoekjes', g: 300 },
  { kw: 'schoonmaakdoekjes', g: 300 },
  { kw: 'vuilniszakken', g: 300 },
  { kw: 'aluminiumfolie', g: 200 },
  { kw: 'vershoudfolie', g: 150 },
  { kw: 'handzeep', g: 350 },
  { kw: 'zeep', g: 150 },
  { kw: 'shampoo', g: 350 },
  { kw: 'crèmespoeling', g: 350 },
  { kw: 'cremespoeling', g: 350 },
  { kw: 'douchegel', g: 300 },
  { kw: 'douchezeep', g: 300 },
  { kw: 'tandpasta', g: 120 },
  { kw: 'tandenborstel elektrisch', g: 250 },
  { kw: 'tandenborstel', g: 30 },
  { kw: 'deodorant', g: 150 },
  { kw: 'zonnebrand', g: 220 },
  { kw: 'aftersun', g: 220 },
  { kw: 'droogshampoo', g: 200 },
  { kw: 'haarspray', g: 250 },
  { kw: 'haargel', g: 170 },
  { kw: 'föhn', g: 550 },
  { kw: 'fohn', g: 550 },
  { kw: 'scheerapparaat', g: 250 },
  { kw: 'luiers', g: 800 },
  { kw: 'billendoekjes', g: 600 },
  { kw: 'tampons', g: 80 },
  { kw: 'maandverband', g: 100 },
  { kw: 'inlegkruisjes', g: 60 },
  { kw: 'lenzenvloeistof', g: 400 },
  { kw: 'lenzen', g: 30 },
  { kw: 'make-up', g: 300 },
  { kw: 'geurtje', g: 200 },
  { kw: 'parfum', g: 200 },

  /* ---- mini-apotheek ---- */
  { kw: 'paracetamol', g: 50 },
  { kw: 'ibuprofen', g: 50 },
  { kw: 'zetpillen', g: 60 },
  { kw: 'melatonine', g: 30 },
  { kw: 'vitamines', g: 150 },
  { kw: 'pleisters', g: 50 },
  { kw: 'wondspray', g: 80 },
  { kw: 'muggenspray', g: 150 },
  { kw: 'anti-mug', g: 150 },
  { kw: 'deet', g: 150 },
  { kw: 'tekentang', g: 15 },
  { kw: 'pincet', g: 20 },
  { kw: 'nagelknipper', g: 30 },
  { kw: 'vaseline', g: 120 },
  { kw: 'ehbo', g: 600 },
  { kw: 'verbanddoos', g: 600 },

  /* ---- keuken & koken ---- */
  { kw: 'pannenset', g: 3000 },
  { kw: 'koekenpan', g: 700 },
  { kw: 'steelpan', g: 500 },
  { kw: 'braadpan', g: 1500 },
  { kw: 'pan', g: 800 },
  { kw: 'fluitketel', g: 700 },
  { kw: 'waterkoker', g: 1000 },
  { kw: 'koffiezetapparaat', g: 2500 },
  { kw: 'senseo', g: 1500 },
  { kw: 'tosti-ijzer', g: 1500 },
  { kw: 'bakplaatje', g: 1200 },
  { kw: 'gourmetstel', g: 3500 },
  { kw: 'bestek', g: 800 },
  { kw: 'bord', g: 300 },
  { kw: 'borden', g: 1200 },
  { kw: 'beker', g: 250 },
  { kw: 'mok', g: 300 },
  { kw: 'glazen', g: 800 },
  { kw: 'glas', g: 200 },
  { kw: 'dopper', g: 100 },
  { kw: 'snijplank', g: 300 },
  { kw: 'mes', g: 100 },
  { kw: 'vergiet', g: 250 },
  { kw: 'afdruiprek', g: 400 },
  { kw: 'theedoek', g: 100 },

  /* ---- kamperen & buiten ---- */
  { kw: 'campingstoel', g: 3000 },
  { kw: 'kampeerstoel', g: 3000 },
  { kw: 'vouwstoel', g: 2500 },
  { kw: 'stoel', g: 3000 },
  { kw: 'campingtafel', g: 4000 },
  { kw: 'tafel', g: 5000 },
  { kw: 'ligbed', g: 3500 },
  { kw: 'parasol', g: 2000 },
  { kw: 'windscherm', g: 2500 },
  { kw: 'grondzeil', g: 1500 },
  { kw: 'worteldoek', g: 2000 },
  { kw: 'tent', g: 4000 },
  { kw: 'luifel', g: 8000 },
  { kw: 'haringen', g: 500 },
  { kw: 'scheerlijnen', g: 200 },
  { kw: 'bbq', g: 5000 },
  { kw: 'barbecue', g: 5000 },
  { kw: 'gasfles', g: 11000 },
  { kw: 'gasbusje', g: 400 },
  { kw: 'jerrycan', g: 1000 },
  { kw: 'watertank', g: 1500 },
  { kw: 'verlengsnoer', g: 1500 },
  { kw: 'kabelhaspel', g: 3000 },
  { kw: 'stroomkabel', g: 2000 },
  { kw: 'adapter', g: 200 },
  { kw: 'oprijblokken', g: 2500 },
  { kw: 'waterpas', g: 300 },
  { kw: 'fietsendrager', g: 15000 },
  { kw: 'e-bike', g: 25000 },
  { kw: 'elektrische fiets', g: 25000 },
  { kw: 'fiets', g: 12000 },
  { kw: 'stepje', g: 4000 },
  { kw: 'step', g: 4000 },

  /* ---- slapen & textiel ---- */
  { kw: 'slaapzak', g: 1500 },
  { kw: 'dekbed', g: 2000 },
  { kw: 'deken', g: 1200 },
  { kw: 'kussen', g: 700 },
  { kw: 'hoeslaken', g: 400 },
  { kw: 'dekbedovertrek', g: 800 },
  { kw: 'strandlaken', g: 600 },
  { kw: 'zwembadhanddoek', g: 600 },
  { kw: 'handdoek', g: 400 },
  { kw: 'washandje', g: 50 },
  { kw: 'wastas', g: 500 },

  /* ---- kleding & schoenen (per stuk/paar) ---- */
  { kw: 'winterjas', g: 1200 },
  { kw: 'regenjas', g: 600 },
  { kw: 'jas', g: 800 },
  { kw: 'hoody', g: 550 },
  { kw: 'trui', g: 500 },
  { kw: 'shirt', g: 200 },
  { kw: 'hempje', g: 120 },
  { kw: 'broek', g: 500 },
  { kw: 'chillbroek', g: 400 },
  { kw: 'pyjama', g: 300 },
  { kw: 'zwembroek', g: 150 },
  { kw: 'bikini', g: 150 },
  { kw: 'sokken', g: 60 },
  { kw: 'ondergoed', g: 60 },
  { kw: 'bh', g: 80 },
  { kw: 'muts', g: 80 },
  { kw: 'pet', g: 80 },
  { kw: 'handschoenen', g: 100 },
  { kw: 'hardloopschoenen', g: 700 },
  { kw: 'wandelschoenen', g: 1200 },
  { kw: 'laarzen', g: 1500 },
  { kw: 'slippers', g: 300 },
  { kw: 'pantoffels', g: 400 },
  { kw: 'schoenen', g: 800 },
  { kw: 'zonnebril', g: 30 },

  /* ---- elektronica ---- */
  { kw: 'laptop', g: 1500 },
  { kw: 'ipad', g: 500 },
  { kw: 'tablet', g: 500 },
  { kw: 'telefoon', g: 200 },
  { kw: 'oplader', g: 100 },
  { kw: 'powerbank', g: 350 },
  { kw: 'koptelefoon', g: 250 },
  { kw: 'oordopjes', g: 60 },
  { kw: 'jbl', g: 600 },
  { kw: 'speaker', g: 600 },
  { kw: 'box', g: 600 },
  { kw: 'walkietalkie', g: 200 },
  { kw: 'zaklamp', g: 200 },
  { kw: 'lantaarn', g: 400 },
  { kw: 'wekker', g: 150 },
  { kw: 'horloge', g: 60 },
  { kw: 'garmin', g: 60 },
  { kw: 'camera', g: 500 },
  { kw: 'drone', g: 900 },

  /* ---- gereedschap & veiligheid ---- */
  { kw: 'gereedschapskist', g: 4000 },
  { kw: 'gereedschap', g: 2000 },
  { kw: 'schroevendraaier', g: 150 },
  { kw: 'tang', g: 200 },
  { kw: 'hamer', g: 600 },
  { kw: 'duct tape', g: 200 },
  { kw: 'tape', g: 150 },
  { kw: 'tie-wraps', g: 100 },
  { kw: 'brandblusser', g: 2500 },
  { kw: 'gevarendriehoek', g: 800 },
  { kw: 'veiligheidshesje', g: 150 },
  { kw: 'sleepkabel', g: 1500 },
  { kw: 'startkabels', g: 1800 },
  { kw: 'krik', g: 2500 },
  { kw: 'reservewiel', g: 18000 },
  { kw: 'vw-tabletten', g: 300 },

  /* ---- spel & strand ---- */
  { kw: '30 seconds', g: 900 },
  { kw: 'hitster', g: 400 },
  { kw: 'regenwormen', g: 250 },
  { kw: 'perudo', g: 350 },
  { kw: 'balletje balletje', g: 200 },
  { kw: 'kaartspel', g: 100 },
  { kw: 'bordspel', g: 900 },
  { kw: 'spelletje', g: 400 },
  { kw: 'spel', g: 400 },
  { kw: 'puzzel', g: 500 },
  { kw: 'leesboek', g: 350 },
  { kw: 'boek', g: 350 },
  { kw: 'zwembandjes', g: 150 },
  { kw: 'zwemband', g: 300 },
  { kw: 'duikbril', g: 150 },
  { kw: 'snorkel', g: 150 },
  { kw: 'plankje zwembad', g: 250 },
  { kw: 'zandbakspullen', g: 600 },
  { kw: 'zandbakspeelgoed', g: 600 },
  { kw: 'speelgoed', g: 500 },
  { kw: 'knuffel', g: 200 },
  { kw: 'bal', g: 300 },
  { kw: 'vlieger', g: 250 },

  /* ---- tassen ---- */
  { kw: 'eastpak', g: 700 },
  { kw: 'rugtas', g: 600 },
  { kw: 'rugzak', g: 600 },
  { kw: 'telefoontasje', g: 150 },
  { kw: 'koffer', g: 3500 },
  { kw: 'tas', g: 500 },
];

/* Geeft het geschatte gewicht in gram, of null als er geen match is.
   Langste trefwoord wint, zodat specifieke termen boven generieke gaan. */
export function schatGewicht(naam) {
  const n = String(naam || '').toLowerCase().trim();
  if (!n) return null;
  let best = null;
  for (const w of WEIGHTS) {
    if (n.indexOf(w.kw) !== -1 && (!best || w.kw.length > best.kw.length)) best = w;
  }
  return best ? best.g : null;
}
